name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults

dependencies:
  - python={{ cookiecutter.pyver }}
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements/dev.txt
