name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - defaults

dependencies:
  - python={{ cookiecutter.pyver }}
  - pip
  - invoke
  - pip-compile
  - pre-commit
  - sphinx
  - sphinxcontrib-apidoc
  - recommonmark
  - nbsphinx
  - ipykernel
  - sphinx_rtd_theme
  - black
  - isort
  - pytype
  - yamlint
  - jupyter-repo2docker
  - pip:
    - sphinxcontrib-katex==0.7.1
    - wemake-python-styleguide
